### ISSUE TITLE
Patch does not work for packages that don't immediately cd into the source directory

### ISSUE THREAD

**Issue by evaryont** [ava1ar/customizepkg#13]
For example, [the package kdeplasma-applets-menubar-archway-bzr](https://aur.archlinux.org/packages/kdeplasma-applets-menubar-archway-bzr/):

```shell
# ...
build() {
  [ -f build ] && rm build
  [ -d build ] || mkdir build
  cd build
  cmake ../$pkgname \
# ...
```

After running customizepkg:

```shell
build() {
  [ -f build ] && rm build
patch -Np1 -i remove_right_icon.diff
  [ -d build ] || mkdir build
  cd build
```

And then patch breaks, because the diff expects to be in build/, where the source code is.

**Comment by ava1ar** [comment]
I believe for such PKGBUILD replace can be used to insert the patch string to the correct location, so I think we can live with this patch command limitation.

**Comment by evaryont** [comment]
Or, for anyone else that might stumble upon this, they could also use the newly added addline action as well.
