### ISSUE TITLE
Failure when # in quoted string

### ISSUE THREAD

**Issue by Frans-Willem** [ava1ar/customizepkg#18]
Line 158 of customizepkg:
eval $(grep -Po '^[[:blank:]]*_?(pkg.*|name)=[^#]*(?= *#|$)' ./PKGBUILD)

fails on the slic3r-git package:
https://aur4.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=slic3r-git

The regular expression is unable to handle the fact that a # appears inside of a quoted string, as in line 118 of the PKGBUILD:
_pkgver="$(awk '/#define SLIC3R_VERSION/ {gsub(/"/, "", $3); print $3 }' ./xs/src/libslic3r/libslic3r.h).$(git rev-parse --short HEAD)"

Any chance we can get this sorted?

**Comment by ava1ar** [comment]
Thanks for the reporting, issue identified and reproduced. Truing to find a solution which won't break existing functionality.

**Comment by ava1ar** [comment]
Fixed in commit #46
