### ISSUE TITLE
addline global is broken

### ISSUE THREAD

**Issue by bartoszek** [ava1ar/customizepkg#21]
#Sed implies global when appending. Extra '/g' switch results with 'g' beeing added to the end of the line (when using 'addline' with global context)

**Comment by ava1ar** [comment]
Can you please provide example of PKGBUILD and customization to reproduce the problem. Thanks!

**Comment by bartoszek** [comment]
/etc/customizepkg.d/luxrays-hg
`addline#global#\.$#for file in `grep lboost_python -l -R ` ;do sed -i 's/$/ -lpython3/' $file ; done
remove#sources#force_python3.diff
replace#global#patch -Np1 < "$srcdir/force_python3.diff"#patch -Np1 < "$srcdir/python3.patch"
replace#package#3.4#3.5
#patch#1#python3.patch`
PKGBUILD [from AUR](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=luxrays-hg)
output of customizepkg (partial) 
` build() {
@@ -41,6 +41,7 @@
     -DCMAKE_SKIP_RPATH=ON \
     -DLUXRAYS_DISABLE_OPENCL=OFF \
     .
+for file in `grep lboost_python -l -R ` ;do sed -i 's/$/ -lpython3/' $file ; doneg
   make
 }
`

I just remove extra 'g' from line 104 and forgot about the issue, sorry for the delay.

**Comment by ava1ar** [comment]
Resolved in commit #52
