### ISSUE TITLE
New grep version crashes customizepkg

### ISSUE THREAD

**Issue by bartoszek** [ava1ar/customizepkg#25]
New grep 2.24.1 throws error about insecure usage of $ and ^ in perl type regexp when '-z' is enebled.
This is a fix around pcre mishandling those type of patterns [grep commit](http://git.savannah.gnu.org/cgit/grep.git/commit/?id=b45641c374a4e34a351ecee61334be0c5c9c4341)
Fix: remove '-z' flag (multi-line fields rarely if ever appears in PKGBUILD )

**Comment by stevenhoneyman** [comment]
Tell that to qemu... https://projects.archlinux.org/svntogit/packages.git/plain/trunk/PKGBUILD?h=packages/qemu

**Comment by stevenhoneyman** [comment]
(I'm not disagreeing that this is a problem, but this needs a real fix, not just a workaround that breaks packages)

**Comment by ava1ar** [comment]
I reverted the multiline change, so customizepkg works now (but not for multiline fields). Multiline support isue discussed here: https://github.com/ava1ar/customizepkg/issues/19
